

name: Debug APK Builder

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: JDK 8 Setup
        uses: actions/setup-java@v1
        with:
          java-version: 11.0.8

      - name: Install NDK
        run: echo "y" | sudo ${ANDROID_HOME}/tools/bin/sdkmanager --install "ndk;21.0.6113669"

      - name: Grant rights
        run: chmod +x ./gradlew

      - name: Build project
        run: ./gradlew build

      - name: Build APK
        run: ./gradlew assembleDebug

      - name: Upload to Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: 'MicroG'
          path: play-services-core/build/outputs/apk/debug/play-services-core-debug.apk
